import type { MujocoViewerOptionDescriptor } from './types'

export const DEFAULT_MUJOCO_VIEWER_OPTION_DESCRIPTORS: MujocoViewerOptionDescriptor[] = [
  {
    id: 'joint',
    label: '关节',
    group: 'overlay',
    category: 'joints',
    description: '显示可交互关节与轴向标记',
    enabledByDefault: false,
  },
  {
    id: 'perturb-object',
    label: '被扰动物体',
    group: 'overlay',
    category: 'selection',
    description: '高亮当前被鼠标扰动的对象',
    enabledByDefault: true,
  },
  {
    id: 'perturb-force',
    label: '扰动力',
    group: 'overlay',
    category: 'forces',
    description: '显示鼠标拖拽时施加到刚体的力向量',
    enabledByDefault: true,
  },
  {
    id: 'tendon',
    label: '绳索/肌腱',
    group: 'overlay',
    category: 'transforms',
    description: '显示 MuJoCo spatial tendon 的动态路径',
    enabledByDefault: true,
  },
  {
    id: 'site',
    label: 'Site 标记',
    group: 'overlay',
    category: 'transforms',
    description: '显示 MJCF site 的调试形状与运行时位置',
    enabledByDefault: false,
  },
  {
    id: 'camera-frustum',
    label: '相机视锥',
    group: 'overlay',
    category: 'cameras',
    description: '显示 MJCF camera 的 marker 与视锥线框',
    enabledByDefault: false,
  },
  {
    id: 'unsupported-placeholders',
    label: '不支持对象占位',
    group: 'overlay',
    category: 'debug',
    description: '显示 SDF 等暂未完整渲染对象的告警占位',
    enabledByDefault: true,
  },
  {
    id: 'skin',
    label: 'Skin',
    group: 'overlay',
    category: 'debug',
    description: '显示 deformable skin；字段缺失时仅给出诊断',
    enabledByDefault: true,
  },
  {
    id: 'flex',
    label: 'Flex',
    group: 'overlay',
    category: 'debug',
    description: '显示 deformable flex；字段缺失时仅给出诊断',
    enabledByDefault: true,
  },
  {
    id: 'flex-wireframe',
    label: 'Flex 线框',
    group: 'appearance',
    category: 'debug',
    description: '以线框方式显示 flex 表面',
    enabledByDefault: false,
  },
  {
    id: 'sensor-marker',
    label: '传感器标记',
    group: 'overlay',
    category: 'debug',
    description: '显示可定位传感器的空间标记',
    enabledByDefault: false,
  },
  {
    id: 'equality',
    label: '约束关系',
    group: 'overlay',
    category: 'debug',
    description: '显示 equality 约束的调试覆盖层',
    enabledByDefault: false,
  },
  {
    id: 'group-filter',
    label: 'Group 过滤',
    group: 'overlay',
    category: 'debug',
    description: '启用对象 group 可见性过滤入口',
    enabledByDefault: false,
  },
  {
    id: 'select-point',
    label: '选中点',
    group: 'overlay',
    category: 'selection',
    description: '显示当前鼠标点击命中的瞬时选中点',
    enabledByDefault: true,
  },
  {
    id: 'contact-point',
    label: '接触点',
    group: 'overlay',
    category: 'contacts',
    description: '显示当前接触位置的调试标记',
    enabledByDefault: false,
  },
  {
    id: 'contact-force',
    label: '接触力',
    group: 'overlay',
    category: 'contacts',
    description: '显示接触点处的接触力向量',
    enabledByDefault: false,
  },
  {
    id: 'center-of-mass',
    label: '质心',
    group: 'overlay',
    category: 'transforms',
    description: '显示 body 质心和系统总质心',
    enabledByDefault: false,
  },
  {
    id: 'inertia',
    label: '等效惯性盒',
    group: 'overlay',
    category: 'inertia',
    description: '显示 body 的等效惯性盒',
    enabledByDefault: false,
  },
  {
    id: 'wireframe',
    label: '线框',
    group: 'appearance',
    category: 'materials',
    description: '按线框方式显示全部仿真几何体',
    enabledByDefault: false,
  },
  {
    id: 'transparent',
    label: '动态物体半透明',
    group: 'appearance',
    category: 'materials',
    description: '让动态几何体变得更透明，方便观察内部结构',
    enabledByDefault: false,
  },
  {
    id: 'reflection',
    label: '反射',
    group: 'environment',
    category: 'rendering',
    description: '在存在地面时启用地面反射效果',
    enabledByDefault: true,
  },
  {
    id: 'additive',
    label: '加法透明',
    group: 'appearance',
    category: 'rendering',
    description: '透明物体改用加法混合，重叠区域更亮',
    enabledByDefault: false,
  },
  {
    id: 'shadow',
    label: '阴影',
    group: 'environment',
    category: 'rendering',
    description: '启用阴影投射与接收',
    enabledByDefault: true,
  },
  {
    id: 'fog',
    label: '雾',
    group: 'environment',
    category: 'rendering',
    description: '让远处物体按距离逐渐雾化',
    enabledByDefault: false,
  },
]
